import React from "react";

const CityList = [
    { key: "", text: "", value: "" },
  { key: "Acton", text: "Acton", value: "Acton" },
  { key: "Adelanto", text: "Adelanto", value: "Adelanto" },
  { key: "Agoura Hills", text: "Agoura Hills", value: "Agoura Hills" },
  { key: "Alameda", text: "Alameda", value: "Alameda" },
  { key: "Alamo", text: "Alamo", value: "Alamo" },
  { key: "Albany", text: "Albany", value: "Albany" },
  { key: "Alhambra", text: "Alhambra", value: "Alhambra" },
  { key: "Aliso Viejo", text: "Aliso Viejo", value: "Aliso Viejo" },
  { key: "Almanor", text: "Almanor", value: "Almanor" },
  { key: "Alondra Park", text: "Alondra Park", value: "Alondra Park" },
  { key: "Alpaugh", text: "Alpaugh", value: "Alpaugh" },
  { key: "Alpine", text: "Alpine", value: "Alpine" },
  { key: "Alpin Village", text: "Alpin Village", value: "Alpin Village" },
  { key: "Altadena", text: "Altadena", value: "Altadena" },
  { key: "Alta Sierra", text: "Alta Sierra", value: "Alta Sierra" },
  { key: "Alturas", text: "Alturas", value: "Alturas" },
  { key: "Alum Rock", text: "Alum Rock", value: "Alum Rock" },
  { key: "Amador City", text: "Amador City", value: "Amador City" },
  { key: "American Canyon", text: "American Canyon", value: "American Canyon" },
  { key: "Amesti", text: "Amesti", value: "Amesti" },
  { key: "Anaheim", text: "Anaheim", value: "Anaheim" },
  { key: "Anderson", text: "Anderson", value: "Anderson" },
  { key: "Angel City", text: "Angel City", value: "Angel City" },
  { key: "Angwin", text: "Angwin", value: "Angwin" },
  { key: "Antioch", text: "Antioch", value: "Antioch" },
  { key: "Apple Valley", text: "Apple Valley", value: "Apple Valley" },
  { key: "Aptos", text: "Aptos", value: "Aptos" },
  {
    key: "Aptos Hills-Larkin Valley",
    text: "Aptos Hills-Larkin Valley",
    value: "Aptos Hills-Larkin Valley"
  },
  { key: "Arbuckle", text: "Arbuckle", value: "Arbuckle" },
  { key: "Arcadia", text: "Arcadia", value: "Arcadia" },
  { key: "Arcata", text: "Arcata", value: "Arcata" },
  { key: "Arden-Arcade", text: "Arden-Arcade", value: "Arden-Arcade" },
  { key: "Armona", text: "Armona", value: "Armona" },
  { key: "Arnold", text: "Arnold", value: "Arnold" },
  { key: "Aromas", text: "Aromas", value: "Aromas" },
  { key: "Arroyo Grande", text: "Arroyo Grande", value: "Arroyo Grande" },
  { key: "Artesia", text: "Artesia", value: "Artesia" },
  { key: "Arvin", text: "Arvin", value: "Arvin" },
  { key: "Ashland", text: "Ashland", value: "Ashland" },
  { key: "Atascradero", text: "Atascradero", value: "Atascradero" },
  { key: "Atherton", text: "Atherton", value: "Atherton" },
  { key: "Atwater", text: "Atwater", value: "Atwater" },
  { key: "Auberry", text: "Auberry", value: "Auberry" },
  { key: "Auburn", text: "Auburn", value: "Auburn" },
  { key: "August", text: "August", value: "August" },
  { key: "Avalon", text: "Avalon", value: "Avalon" },
  { key: "Avenal", text: "Avenal", value: "Avenal" },
  { key: "Avery", text: "Avery", value: "Avery" },
  { key: "Avocado Heights", text: "Avocado Heights", value: "Avocado Heights" },
  { key: "Azusa", text: "Azusa", value: "Azusa" },
  { key: "Bakersfield", text: "Bakersfield", value: "Bakersfield" },
  { key: "Baldwin Park", text: "Baldwin Park", value: "Baldwin Park" },
  { key: "Banning", text: "Banning", value: "Banning" },
  { key: "Barstow", text: "Barstow", value: "Barstow" },
  { key: "Bay Point", text: "Bay Point", value: "Bay Point" },
  { key: "Bayview", text: "Bayview", value: "Bayview" },
  {
    key: "Bayview-Montalvin",
    text: "Bayview-Montalvin",
    value: "Bayview-Montalvin"
  },
  {
    key: "Baywood-Los Osos",
    text: "Baywood-Los Osos",
    value: "Baywood-Los Osos"
  },
  { key: "Beale AFB", text: "Beale AFB", value: "Beale AFB" },
  { key: "Bear Valley", text: "Bear Valley", value: "Bear Valley" },
  {
    key: "Bear Valley Springs",
    text: "Bear Valley Springs",
    value: "Bear Valley Springs"
  },
  { key: "Beaumont", text: "Beaumont", value: "Beaumont" },
  { key: "Beckwourth", text: "Beckwourth", value: "Beckwourth" },
  { key: "Belden", text: "Belden", value: "Belden" },
  { key: "Bell", text: "Bell", value: "Bell" },
  { key: "Bellflower", text: "Bellflower", value: "Bellflower" },
  { key: "Bell Gardens", text: "Bell Gardens", value: "Bell Gardens" },
  { key: "Belmont", text: "Belmont", value: "Belmont" },
  { key: "Belvedere", text: "Belvedere", value: "Belvedere" },
  { key: "Benicia", text: "Benicia", value: "Benicia" },
  { key: "Ben Lomond", text: "Ben Lomond", value: "Ben Lomond" },
  { key: "Berkeley", text: "Berkeley", value: "Berkeley" },
  { key: "Bermuda Dunes", text: "Bermuda Dunes", value: "Bermuda Dunes" },
  {
    key: "Bertsch-Oceanview",
    text: "Bertsch-Oceanview",
    value: "Bertsch-Oceanview"
  },
  { key: "Bethel Island", text: "Bethel Island", value: "Bethel Island" },
  { key: "Beverly Hills", text: "Beverly Hills", value: "Beverly Hills" },
  { key: "Big Bear City", text: "Big Bear City", value: "Big Bear City" },
  { key: "Big Bear Lake", text: "Big Bear Lake", value: "Big Bear Lake" },
  { key: "Big Bend", text: "Big Bend", value: "Big Bend" },
  { key: "Biggs", text: "Biggs", value: "Biggs" },
  { key: "Big Pine", text: "Big Pine", value: "Big Pine" },
  { key: "Big River", text: "Big River", value: "Big River" },
  { key: "Biola", text: "Biola", value: "Biola" },
  { key: "Bishop", text: "Bishop", value: "Bishop" },
  {
    key: "Blackhawk-Camino Tassajara",
    text: "Blackhawk-Camino Tassajara",
    value: "Blackhawk-Camino Tassajara"
  },
  {
    key: "Black Point-Green Point",
    text: "Black Point-Green Point",
    value: "Black Point-Green Point"
  },
  { key: "Blairsden", text: "Blairsden", value: "Blairsden" },
  { key: "Bloomington", text: "Bloomington", value: "Bloomington" },
  { key: "Blue Lake", text: "Blue Lake", value: "Blue Lake" },
  { key: "Bluewater", text: "Bluewater", value: "Bluewater" },
  { key: "Blythe", text: "Blythe", value: "Blythe" },
  { key: "Bodega Bay", text: "Bodega Bay", value: "Bodega Bay" },
  { key: "Bodfish", text: "Bodfish", value: "Bodfish" },
  { key: "Bolinas", text: "Bolinas", value: "Bolinas" },
  { key: "Bombay Beach", text: "Bombay Beach", value: "Bombay Beach" },
  {
    key: "Bonadelle Ranchos-Madera Ranchos",
    text: "Bonadelle Ranchos-Madera Ranchos",
    value: "Bonadelle Ranchos-Madera Ranchos"
  },
  { key: "Bonita", text: "Bonita", value: "Bonita" },
  { key: "Bonsall", text: "Bonsall", value: "Bonsall" },
  { key: "Bootjack", text: "Bootjack", value: "Bootjack" },
  { key: "Boron", text: "Boron", value: "Boron" },
  { key: "Boronda", text: "Boronda", value: "Boronda" },
  { key: "Borrego Springs", text: "Borrego Springs", value: "Borrego Springs" },
  { key: "Bostonia", text: "Bostonia", value: "Bostonia" },
  { key: "Boulder Creek", text: "Boulder Creek", value: "Boulder Creek" },
  { key: "Bowles", text: "Bowles", value: "Bowles" },
  {
    key: "Boyes Hot Springs",
    text: "Boyes Hot Springs",
    value: "Boyes Hot Springs"
  },
  { key: "Bradbury", text: "Bradbury", value: "Bradbury" },
  { key: "Bradley", text: "Bradley", value: "Bradley" },
  { key: "Brawley", text: "Brawley", value: "Brawley" },
  { key: "Brea", text: "Brea", value: "Brea" },
  { key: "Brentwood", text: "Brentwood", value: "Brentwood" },
  { key: "Bret Harte", text: "Bret Harte", value: "Bret Harte" },
  { key: "Brisbane", text: "Brisbane", value: "Brisbane" },
  { key: "Broadmoor", text: "Broadmoor", value: "Broadmoor" },
  { key: "Bucks Lake", text: "Bucks Lake", value: "Bucks Lake" },
  { key: "Buellton", text: "Buellton", value: "Buellton" },
  { key: "Buena Park", text: "Buena Park", value: "Buena Park" },
  { key: "Buena Vista", text: "Buena Vista", value: "Buena Vista" },
  { key: "Burbank", text: "Burbank", value: "Burbank" },
  { key: "Burlingame", text: "Burlingame", value: "Burlingame" },
  { key: "Burney", text: "Burney", value: "Burney" },
  { key: "Buttonwillow", text: "Buttonwillow", value: "Buttonwillow" },
  { key: "Byron", text: "Byron", value: "Byron" },
  { key: "Bystrom", text: "Bystrom", value: "Bystrom" },
  { key: "Cabazon", text: "Cabazon", value: "Cabazon" },
  { key: "Calabasas", text: "Calabasas", value: "Calabasas" },
  { key: "Calexico", text: "Calexico", value: "Calexico" },
  { key: "California City", text: "California City", value: "California City" },
  { key: "Calimesa", text: "Calimesa", value: "Calimesa" },
  { key: "Calipatria", text: "Calipatria", value: "Calipatria" },
  { key: "Calistoga", text: "Calistoga", value: "Calistoga" },
  { key: "Calwa", text: "Calwa", value: "Calwa" },
  { key: "Camarillo", text: "Camarillo", value: "Camarillo" },
  { key: "Cambria", text: "Cambria", value: "Cambria" },
  { key: "Cambrian Park", text: "Cambrian Park", value: "Cambrian Park" },
  { key: "Cameron Park", text: "Cameron Park", value: "Cameron Park" },
  { key: "Campbell", text: "Campbell", value: "Campbell" },
  {
    key: "Camp Pendleton North",
    text: "Camp Pendleton North",
    value: "Camp Pendleton North"
  },
  {
    key: "Camp Pendleton South",
    text: "Camp Pendleton South",
    value: "Camp Pendleton South"
  },
  { key: "Cantua Creek", text: "Cantua Creek", value: "Cantua Creek" },
  { key: "Canyondam", text: "Canyondam", value: "Canyondam" },
  { key: "Canyon Lake", text: "Canyon Lake", value: "Canyon Lake" },
  { key: "Capitola", text: "Capitola", value: "Capitola" },
  { key: "Caribou", text: "Caribou", value: "Caribou" },
  { key: "Carlsbad", text: "Carlsbad", value: "Carlsbad" },
  {
    key: "Carmel-by-the-Sea",
    text: "Carmel-by-the-Sea",
    value: "Carmel-by-the-Sea"
  },
  {
    key: "Carmel Valley Village",
    text: "Carmel Valley Village",
    value: "Carmel Valley Village"
  },
  { key: "Carmichael", text: "Carmichael", value: "Carmichael" },
  { key: "Carpinteria", text: "Carpinteria", value: "Carpinteria" },
  { key: "Carrick", text: "Carrick", value: "Carrick" },
  { key: "Carson", text: "Carson", value: "Carson" },
  { key: "Cartago", text: "Cartago", value: "Cartago" },
  { key: "Caruthers", text: "Caruthers", value: "Caruthers" },
  { key: "Casa Conejo", text: "Casa Conejo", value: "Casa Conejo" },
  {
    key: "Casa de Oro-Mount Helix",
    text: "Casa de Oro-Mount Helix",
    value: "Casa de Oro-Mount Helix"
  },
  { key: "Castro Valley", text: "Castro Valley", value: "Castro Valley" },
  { key: "Castroville", text: "Castroville", value: "Castroville" },
  { key: "Cathedral City", text: "Cathedral City", value: "Cathedral City" },
  { key: "Cayucos", text: "Cayucos", value: "Cayucos" },
  { key: "Ceres", text: "Ceres", value: "Ceres" },
  { key: "Cerritos", text: "Cerritos", value: "Cerritos" },
  {
    key: "Challenge-Brownsville",
    text: "Challenge-Brownsville",
    value: "Challenge-Brownsville"
  },
  {
    key: "Channel Islands Beach",
    text: "Channel Islands Beach",
    value: "Channel Islands Beach"
  },
  { key: "Charter Oak", text: "Charter Oak", value: "Charter Oak" },
  { key: "Cherryland", text: "Cherryland", value: "Cherryland" },
  { key: "Cherry Valley", text: "Cherry Valley", value: "Cherry Valley" },
  { key: "Chester", text: "Chester", value: "Chester" },
  { key: "Chico", text: "Chico", value: "Chico" },
  { key: "Chilcoot-Vinton", text: "Chilcoot-Vinton", value: "Chilcoot-Vinton" },
  {
    key: "China Lake Acres",
    text: "China Lake Acres",
    value: "China Lake Acres"
  },
  { key: "Chinese Camp", text: "Chinese Camp", value: "Chinese Camp" },
  { key: "Chino", text: "Chino", value: "Chino" },
  { key: "Chino Hills", text: "Chino Hills", value: "Chino Hills" },
  { key: "Chowchilla", text: "Chowchilla", value: "Chowchilla" },
  { key: "Chualar", text: "Chualar", value: "Chualar" },
  { key: "Chula Vista", text: "Chula Vista", value: "Chula Vista" },
  { key: "Citrus", text: "Citrus", value: "Citrus" },
  { key: "Citrus Heights", text: "Citrus Heights", value: "Citrus Heights" },
  { key: "Claremont", text: "Claremont", value: "Claremont" },
  { key: "Clayton", text: "Clayton", value: "Clayton" },
  { key: "Clearlake", text: "Clearlake", value: "Clearlake" },
  { key: "Clearlake Oaks", text: "Clearlake Oaks", value: "Clearlake Oaks" },
  { key: "Clio", text: "Clio", value: "Clio" },
  { key: "Cloverdale", text: "Cloverdale", value: "Cloverdale" },
  { key: "Clovis", text: "Clovis", value: "Clovis" },
  { key: "Clyde", text: "Clyde", value: "Clyde" },
  { key: "Coachella", text: "Coachella", value: "Coachella" },
  { key: "Coalinga", text: "Coalinga", value: "Coalinga" },
  { key: "Cobb", text: "Cobb", value: "Cobb" },
  { key: "Colfax", text: "Colfax", value: "Colfax" },
  { key: "Colma", text: "Colma", value: "Colma" },
  { key: "Colton", text: "Colton", value: "Colton" },
  { key: "Columbia", text: "Columbia", value: "Columbia" },
  { key: "Colusa", text: "Colusa", value: "Colusa" },
  { key: "Commerce", text: "Commerce", value: "Commerce" },
  { key: "Compton", text: "Compton", value: "Compton" },
  { key: "Concord", text: "Concord", value: "Concord" },
  { key: "Concow", text: "Concow", value: "Concow" },
  { key: "Copperopolis", text: "Copperopolis", value: "Copperopolis" },
  { key: "Corcoran", text: "Corcoran", value: "Corcoran" },
  { key: "Corning", text: "Corning", value: "Corning" },
  { key: "Corona", text: "Corona", value: "Corona" },
  { key: "Coronado", text: "Coronado", value: "Coronado" },
  { key: "Corralitos", text: "Corralitos", value: "Corralitos" },
  { key: "Corte Madera", text: "Corte Madera", value: "Corte Madera" },
  { key: "Costa Mesa", text: "Costa Mesa", value: "Costa Mesa" },
  { key: "Cotati", text: "Cotati", value: "Cotati" },
  { key: "Coto de Caza", text: "Coto de Caza", value: "Coto de Caza" },
  { key: "Cottonwood", text: "Cottonwood", value: "Cottonwood" },
  { key: "Country Club", text: "Country Club", value: "Country Club" },
  { key: "Covelo", text: "Covelo", value: "Covelo" },
  { key: "Covina", text: "Covina", value: "Covina" },
  { key: "Crescent City", text: "Crescent City", value: "Crescent City" },
  {
    key: "Crescent City North",
    text: "Crescent City North",
    value: "Crescent City North"
  },
  { key: "Crescent Mills", text: "Crescent Mills", value: "Crescent Mills" },
  { key: "Crest", text: "Crest", value: "Crest" },
  { key: "Crestline", text: "Crestline", value: "Crestline" },
  { key: "C-Road", text: "C-Road", value: "C-Road" },
  { key: "Crockett", text: "Crockett", value: "Crockett" },
  { key: "Cromberg", text: "Cromberg", value: "Cromberg" },
  { key: "Cudahy", text: "Cudahy", value: "Cudahy" },
  { key: "Culver City", text: "Culver City", value: "Culver City" },
  { key: "Cupertino", text: "Cupertino", value: "Cupertino" },
  { key: "Cutler", text: "Cutler", value: "Cutler" },
  { key: "Cutten", text: "Cutten", value: "Cutten" },
  { key: "Cypress", text: "Cypress", value: "Cypress" },
  { key: "Daly City", text: "Daly City", value: "Daly City" },
  { key: "Dana Point", text: "Dana Point", value: "Dana Point" },
  { key: "Danville", text: "Danville", value: "Danville" },
  { key: "Darwin", text: "Darwin", value: "Darwin" },
  { key: "Davis", text: "Davis", value: "Davis" },
  { key: "Day Valley", text: "Day Valley", value: "Day Valley" },
  { key: "Deer Park", text: "Deer Park", value: "Deer Park" },
  { key: "Del Aire", text: "Del Aire", value: "Del Aire" },
  { key: "Delano", text: "Delano", value: "Delano" },
  { key: "Delhi", text: "Delhi", value: "Delhi" },
  { key: "Delleker", text: "Delleker", value: "Delleker" },
  { key: "Del Mar", text: "Del Mar", value: "Del Mar" },
  {
    key: "Del Monte Forest",
    text: "Del Monte Forest",
    value: "Del Monte Forest"
  },
  { key: "Del Rey", text: "Del Rey", value: "Del Rey" },
  { key: "Del Rey Oaks", text: "Del Rey Oaks", value: "Del Rey Oaks" },
  { key: "Del Rio", text: "Del Rio", value: "Del Rio" },
  { key: "Denair", text: "Denair", value: "Denair" },
  { key: "Derby Acres", text: "Derby Acres", value: "Derby Acres" },
  {
    key: "Desert Hot Springs",
    text: "Desert Hot Springs",
    value: "Desert Hot Springs"
  },
  { key: "Desert Shores", text: "Desert Shores", value: "Desert Shores" },
  {
    key: "Desert View Highlands",
    text: "Desert View Highlands",
    value: "Desert View Highlands"
  },
  { key: "Diablo", text: "Diablo", value: "Diablo" },
  { key: "Diamond Bar", text: "Diamond Bar", value: "Diamond Bar" },
  { key: "Diamond Springs", text: "Diamond Springs", value: "Diamond Springs" },
  { key: "Dillon Beach", text: "Dillon Beach", value: "Dillon Beach" },
  { key: "Dinuba", text: "Dinuba", value: "Dinuba" },
  { key: "Discovery Bay", text: "Discovery Bay", value: "Discovery Bay" },
  { key: "Dixon", text: "Dixon", value: "Dixon" },
  {
    key: "Dixon Lane-Meadow Creek",
    text: "Dixon Lane-Meadow Creek",
    value: "Dixon Lane-Meadow Creek"
  },
  { key: "Dollar Point", text: "Dollar Point", value: "Dollar Point" },
  { key: "Dorrington", text: "Dorrington", value: "Dorrington" },
  { key: "Dorris", text: "Dorris", value: "Dorris" },
  { key: "Dos Palos", text: "Dos Palos", value: "Dos Palos" },
  { key: "Downey", text: "Downey", value: "Downey" },
  { key: "Duarte", text: "Duarte", value: "Duarte" },
  { key: "Dublin", text: "Dublin", value: "Dublin" },
  { key: "Ducor", text: "Ducor", value: "Ducor" },
  { key: "Dunsmuir", text: "Dunsmuir", value: "Dunsmuir" },
  { key: "Durham", text: "Durham", value: "Durham" },
  { key: "Dustin Acres", text: "Dustin Acres", value: "Dustin Acres" },
  { key: "Earlimart", text: "Earlimart", value: "Earlimart" },
  { key: "East Blythe", text: "East Blythe", value: "East Blythe" },
  { key: "East Compton", text: "East Compton", value: "East Compton" },
  { key: "East Foothills", text: "East Foothills", value: "East Foothills" },
  { key: "East Hemet", text: "East Hemet", value: "East Hemet" },
  { key: "East La Mirada", text: "East La Mirada", value: "East La Mirada" },
  {
    key: "East Los Angeles",
    text: "East Los Angeles",
    value: "East Los Angeles"
  },
  { key: "East Oakdale", text: "East Oakdale", value: "East Oakdale" },
  { key: "Easton", text: "Easton", value: "Easton" },
  { key: "East Orosi", text: "East Orosi", value: "East Orosi" },
  { key: "East Palo Alto", text: "East Palo Alto", value: "East Palo Alto" },
  { key: "East Pasadena", text: "East Pasadena", value: "East Pasadena" },
  {
    key: "East Porterville",
    text: "East Porterville",
    value: "East Porterville"
  },
  { key: "East Quincy", text: "East Quincy", value: "East Quincy" },
  {
    key: "East Richmond Heights",
    text: "East Richmond Heights",
    value: "East Richmond Heights"
  },
  {
    key: "East San Gabriel",
    text: "East San Gabriel",
    value: "East San Gabriel"
  },
  { key: "East Shore", text: "East Shore", value: "East Shore" },
  { key: "East Sonora", text: "East Sonora", value: "East Sonora" },
  { key: "Edgewood", text: "Edgewood", value: "Edgewood" },
  { key: "Edwards AFB", text: "Edwards AFB", value: "Edwards AFB" },
  { key: "El Cajon", text: "El Cajon", value: "El Cajon" },
  { key: "El Centro", text: "El Centro", value: "El Centro" },
  { key: "El Cerrito", text: "El Cerrito", value: "El Cerrito" },
  { key: "El Dorado Hills", text: "El Dorado Hills", value: "El Dorado Hills" },
  { key: "Eldridge", text: "Eldridge", value: "Eldridge" },
  { key: "El Granada", text: "El Granada", value: "El Granada" },
  { key: "Elk Grove", text: "Elk Grove", value: "Elk Grove" },
  { key: "Elkhorn", text: "Elkhorn", value: "Elkhorn" },
  { key: "Elmira", text: "Elmira", value: "Elmira" },
  { key: "El Monte", text: "El Monte", value: "El Monte" },
  {
    key: "El Paso de Robles (Paso Robles)",
    text: "El Paso de Robles (Paso Robles)",
    value: "El Paso de Robles (Paso Robles)"
  },
  { key: "El Rio", text: "El Rio", value: "El Rio" },
  { key: "El Segundo", text: "El Segundo", value: "El Segundo" },
  { key: "El Sobrante", text: "El Sobrante", value: "El Sobrante" },
  { key: "El Verano", text: "El Verano", value: "El Verano" },
  {
    key: "Emerald Lake Hills",
    text: "Emerald Lake Hills",
    value: "Emerald Lake Hills"
  },
  { key: "Emeryville", text: "Emeryville", value: "Emeryville" },
  { key: "Empire", text: "Empire", value: "Empire" },
  { key: "Encinitas", text: "Encinitas", value: "Encinitas" },
  { key: "Escalon", text: "Escalon", value: "Escalon" },
  { key: "Escondido", text: "Escondido", value: "Escondido" },
  { key: "Esparto", text: "Esparto", value: "Esparto" },
  { key: "Etna", text: "Etna", value: "Etna" },
  { key: "Eureka", text: "Eureka", value: "Eureka" },
  { key: "Exeter", text: "Exeter", value: "Exeter" },
  { key: "Fairbanks Ranch", text: "Fairbanks Ranch", value: "Fairbanks Ranch" },
  { key: "Fairfax", text: "Fairfax", value: "Fairfax" },
  { key: "Fairfield", text: "Fairfield", value: "Fairfield" },
  { key: "Fair Oaks", text: "Fair Oaks", value: "Fair Oaks" },
  { key: "Fairview", text: "Fairview", value: "Fairview" },
  { key: "Fallbrook", text: "Fallbrook", value: "Fallbrook" },
  {
    key: "Fall River Mills",
    text: "Fall River Mills",
    value: "Fall River Mills"
  },
  { key: "Farmersville", text: "Farmersville", value: "Farmersville" },
  { key: "Farmington", text: "Farmington", value: "Farmington" },
  { key: "Fellows", text: "Fellows", value: "Fellows" },
  { key: "Felton", text: "Felton", value: "Felton" },
  { key: "Ferndale", text: "Ferndale", value: "Ferndale" },
  {
    key: "Fetters Hot Springs-Agua Caliente",
    text: "Fetters Hot Springs-Agua Caliente",
    value: "Fetters Hot Springs-Agua Caliente"
  },
  { key: "Fillmore", text: "Fillmore", value: "Fillmore" },
  { key: "Firebaugh", text: "Firebaugh", value: "Firebaugh" },
  { key: "Florence-Graham", text: "Florence-Graham", value: "Florence-Graham" },
  { key: "Florin", text: "Florin", value: "Florin" },
  { key: "Folsom", text: "Folsom", value: "Folsom" },
  { key: "Fontana", text: "Fontana", value: "Fontana" },
  { key: "Foothill Farms", text: "Foothill Farms", value: "Foothill Farms" },
  { key: "Foothill Ranch", text: "Foothill Ranch", value: "Foothill Ranch" },
  { key: "Ford City", text: "Ford City", value: "Ford City" },
  { key: "Foresthill", text: "Foresthill", value: "Foresthill" },
  { key: "Forest Meadows", text: "Forest Meadows", value: "Forest Meadows" },
  { key: "Forestville", text: "Forestville", value: "Forestville" },
  { key: "Fort Bragg", text: "Fort Bragg", value: "Fort Bragg" },
  { key: "Fort Jones", text: "Fort Jones", value: "Fort Jones" },
  { key: "Fortuna", text: "Fortuna", value: "Fortuna" },
  { key: "Foster City", text: "Foster City", value: "Foster City" },
  { key: "Fountain Valley", text: "Fountain Valley", value: "Fountain Valley" },
  { key: "Fowler", text: "Fowler", value: "Fowler" },
  { key: "Frazier Park", text: "Frazier Park", value: "Frazier Park" },
  { key: "Freedom", text: "Freedom", value: "Freedom" },
  { key: "Fremont", text: "Fremont", value: "Fremont" },
  { key: "French Camp", text: "French Camp", value: "French Camp" },
  { key: "French Gulch", text: "French Gulch", value: "French Gulch" },
  { key: "Fresno", text: "Fresno", value: "Fresno" },
  { key: "Friant", text: "Friant", value: "Friant" },
  { key: "Fruitdale", text: "Fruitdale", value: "Fruitdale" },
  { key: "Fullerton", text: "Fullerton", value: "Fullerton" },
  { key: "Furnace Creek", text: "Furnace Creek", value: "Furnace Creek" },
  { key: "Galt", text: "Galt", value: "Galt" },
  { key: "Gardena", text: "Gardena", value: "Gardena" },
  { key: "Garden Acres", text: "Garden Acres", value: "Garden Acres" },
  { key: "Garden Grove", text: "Garden Grove", value: "Garden Grove" },
  { key: "Gazelle", text: "Gazelle", value: "Gazelle" },
  { key: "Georgetown", text: "Georgetown", value: "Georgetown" },
  {
    key: "Gerber-Las Flores",
    text: "Gerber-Las Flores",
    value: "Gerber-Las Flores"
  },
  { key: "Gilroy", text: "Gilroy", value: "Gilroy" },
  { key: "Glen Avon", text: "Glen Avon", value: "Glen Avon" },
  { key: "Glendale", text: "Glendale", value: "Glendale" },
  { key: "Glendora", text: "Glendora", value: "Glendora" },
  { key: "Glen Ellen", text: "Glen Ellen", value: "Glen Ellen" },
  { key: "Golden Hills", text: "Golden Hills", value: "Golden Hills" },
  { key: "Gold River", text: "Gold River", value: "Gold River" },
  { key: "Goleta", text: "Goleta", value: "Goleta" },
  { key: "Gonzales", text: "Gonzales", value: "Gonzales" },
  { key: "Goshen", text: "Goshen", value: "Goshen" },
  { key: "Graeagle", text: "Graeagle", value: "Graeagle" },
  { key: "Grand Terrace", text: "Grand Terrace", value: "Grand Terrace" },
  { key: "Granite Bay", text: "Granite Bay", value: "Granite Bay" },
  { key: "Granite Hills", text: "Granite Hills", value: "Granite Hills" },
  { key: "Grass Valley", text: "Grass Valley", value: "Grass Valley" },
  { key: "Graton", text: "Graton", value: "Graton" },
  { key: "Grayson", text: "Grayson", value: "Grayson" },
  { key: "Greenfield", text: "Greenfield", value: "Greenfield" },
  { key: "Greenhorn", text: "Greenhorn", value: "Greenhorn" },
  { key: "Green Valley", text: "Green Valley", value: "Green Valley" },
  { key: "Greenview", text: "Greenview", value: "Greenview" },
  { key: "Greenville", text: "Greenville", value: "Greenville" },
  { key: "Grenada", text: "Grenada", value: "Grenada" },
  { key: "Gridley", text: "Gridley", value: "Gridley" },
  {
    key: "Groveland-Big Oak Flat",
    text: "Groveland-Big Oak Flat",
    value: "Groveland-Big Oak Flat"
  },
  { key: "Grover Beach", text: "Grover Beach", value: "Grover Beach" },
  { key: "Guadalupe", text: "Guadalupe", value: "Guadalupe" },
  { key: "Guerneville", text: "Guerneville", value: "Guerneville" },
  { key: "Gustine", text: "Gustine", value: "Gustine" },
  {
    key: "Hacienda Heights",
    text: "Hacienda Heights",
    value: "Hacienda Heights"
  },
  { key: "Half Moon Bay", text: "Half Moon Bay", value: "Half Moon Bay" },
  { key: "Hamilton Branch", text: "Hamilton Branch", value: "Hamilton Branch" },
  { key: "Hamilton City", text: "Hamilton City", value: "Hamilton City" },
  { key: "Hanford", text: "Hanford", value: "Hanford" },
  { key: "Harbison Canyon", text: "Harbison Canyon", value: "Harbison Canyon" },
  {
    key: "Hawaiian Gardens",
    text: "Hawaiian Gardens",
    value: "Hawaiian Gardens"
  },
  { key: "Hawthorne", text: "Hawthorne", value: "Hawthorne" },
  { key: "Hayfork", text: "Hayfork", value: "Hayfork" },
  { key: "Hayward", text: "Hayward", value: "Hayward" },
  { key: "Healdsburg", text: "Healdsburg", value: "Healdsburg" },
  { key: "Heber", text: "Heber", value: "Heber" },
  { key: "Hemet", text: "Hemet", value: "Hemet" },
  { key: "Hercules", text: "Hercules", value: "Hercules" },
  { key: "Hermosa Beach", text: "Hermosa Beach", value: "Hermosa Beach" },
  { key: "Hesperia", text: "Hesperia", value: "Hesperia" },
  { key: "Hickman", text: "Hickman", value: "Hickman" },
  { key: "Hidden Hills", text: "Hidden Hills", value: "Hidden Hills" },
  { key: "Hidden Meadows", text: "Hidden Meadows", value: "Hidden Meadows" },
  {
    key: "Hidden Valley Lake",
    text: "Hidden Valley Lake",
    value: "Hidden Valley Lake"
  },
  { key: "Highgrove", text: "Highgrove", value: "Highgrove" },
  { key: "Highland", text: "Highland", value: "Highland" },
  {
    key: "Highlands-Baywood Park",
    text: "Highlands-Baywood Park",
    value: "Highlands-Baywood Park"
  },
  { key: "Hillsborough", text: "Hillsborough", value: "Hillsborough" },
  { key: "Hilmar-Irwin", text: "Hilmar-Irwin", value: "Hilmar-Irwin" },
  { key: "Hollister", text: "Hollister", value: "Hollister" },
  { key: "Holtville", text: "Holtville", value: "Holtville" },
  { key: "Home Garden", text: "Home Garden", value: "Home Garden" },
  { key: "Home Gardens", text: "Home Gardens", value: "Home Gardens" },
  { key: "Homeland", text: "Homeland", value: "Homeland" },
  {
    key: "Homewood Canyon-Valley Wells",
    text: "Homewood Canyon-Valley Wells",
    value: "Homewood Canyon-Valley Wells"
  },
  { key: "Hornbrook", text: "Hornbrook", value: "Hornbrook" },
  { key: "Hughson", text: "Hughson", value: "Hughson" },
  { key: "Humboldt Hill", text: "Humboldt Hill", value: "Humboldt Hill" },
  {
    key: "Huntington Beach",
    text: "Huntington Beach",
    value: "Huntington Beach"
  },
  { key: "Huntington Park", text: "Huntington Park", value: "Huntington Park" },
  { key: "Huron", text: "Huron", value: "Huron" },
  { key: "Hydesville", text: "Hydesville", value: "Hydesville" },
  {
    key: "Idyllwild-Pine Cove",
    text: "Idyllwild-Pine Cove",
    value: "Idyllwild-Pine Cove"
  },
  { key: "Imperial", text: "Imperial", value: "Imperial" },
  { key: "Imperial Beach", text: "Imperial Beach", value: "Imperial Beach" },
  { key: "Independence", text: "Independence", value: "Independence" },
  { key: "Indian Falls", text: "Indian Falls", value: "Indian Falls" },
  { key: "Indian Wells", text: "Indian Wells", value: "Indian Wells" },
  { key: "Indio", text: "Indio", value: "Indio" },
  { key: "Industry", text: "Industry", value: "Industry" },
  { key: "Inglewood", text: "Inglewood", value: "Inglewood" },
  { key: "Interlaken", text: "Interlaken", value: "Interlaken" },
  { key: "Inverness", text: "Inverness", value: "Inverness" },
  { key: "Inyokern", text: "Inyokern", value: "Inyokern" },
  { key: "Ione", text: "Ione", value: "Ione" },
  { key: "Iron Horse", text: "Iron Horse", value: "Iron Horse" },
  { key: "Irvine", text: "Irvine", value: "Irvine" },
  { key: "Irwindale", text: "Irwindale", value: "Irwindale" },
  { key: "Isla Vista", text: "Isla Vista", value: "Isla Vista" },
  { key: "Isleton", text: "Isleton", value: "Isleton" },
  { key: "Ivanhoe", text: "Ivanhoe", value: "Ivanhoe" },
  { key: "Jackson", text: "Jackson", value: "Jackson" },
  { key: "Jamestown", text: "Jamestown", value: "Jamestown" },
  { key: "Jamul", text: "Jamul", value: "Jamul" },
  { key: "Johannesburg", text: "Johannesburg", value: "Johannesburg" },
  { key: "Johnsville", text: "Johnsville", value: "Johnsville" },
  { key: "Joshua Tree", text: "Joshua Tree", value: "Joshua Tree" },
  { key: "Julian", text: "Julian", value: "Julian" },
  { key: "Keddie", text: "Keddie", value: "Keddie" },
  { key: "Keeler", text: "Keeler", value: "Keeler" },
  { key: "Keene", text: "Keene", value: "Keene" },
  { key: "Kelseyville", text: "Kelseyville", value: "Kelseyville" },
  { key: "Kennedy", text: "Kennedy", value: "Kennedy" },
  { key: "Kensington", text: "Kensington", value: "Kensington" },
  { key: "Kentfield", text: "Kentfield", value: "Kentfield" },
  { key: "Kerman", text: "Kerman", value: "Kerman" },
  { key: "Kernville", text: "Kernville", value: "Kernville" },
  { key: "Kettleman City", text: "Kettleman City", value: "Kettleman City" },
  { key: "Keyes", text: "Keyes", value: "Keyes" },
  { key: "King City", text: "King City", value: "King City" },
  { key: "Kings Beach", text: "Kings Beach", value: "Kings Beach" },
  { key: "Kingsburg", text: "Kingsburg", value: "Kingsburg" },
  { key: "Kirkwood", text: "Kirkwood", value: "Kirkwood" },
  { key: "Klamath", text: "Klamath", value: "Klamath" },
  { key: "Knightsen", text: "Knightsen", value: "Knightsen" },
  {
    key: "La Canada Flintridge",
    text: "La Canada Flintridge",
    value: "La Canada Flintridge"
  },
  {
    key: "La Crescenta-Montrose",
    text: "La Crescenta-Montrose",
    value: "La Crescenta-Montrose"
  },
  { key: "Ladera Heights", text: "Ladera Heights", value: "Ladera Heights" },
  { key: "Lafayette", text: "Lafayette", value: "Lafayette" },
  { key: "Laguna", text: "Laguna", value: "Laguna" },
  { key: "Laguna Beach", text: "Laguna Beach", value: "Laguna Beach" },
  { key: "Laguna Hills", text: "Laguna Hills", value: "Laguna Hills" },
  { key: "Laguna Niguel", text: "Laguna Niguel", value: "Laguna Niguel" },
  {
    key: "Laguna West-Lakeside",
    text: "Laguna West-Lakeside",
    value: "Laguna West-Lakeside"
  },
  { key: "Laguna Woods", text: "Laguna Woods", value: "Laguna Woods" },
  {
    key: "Lagunitas-Forest Knolls",
    text: "Lagunitas-Forest Knolls",
    value: "Lagunitas-Forest Knolls"
  },
  { key: "La Habra", text: "La Habra", value: "La Habra" },
  {
    key: "La Habra Heights",
    text: "La Habra Heights",
    value: "La Habra Heights"
  },
  {
    key: "Lake Almanor Country Club",
    text: "Lake Almanor Country Club",
    value: "Lake Almanor Country Club"
  },
  {
    key: "Lake Almanor Peninsula",
    text: "Lake Almanor Peninsula",
    value: "Lake Almanor Peninsula"
  },
  {
    key: "Lake Almanor West",
    text: "Lake Almanor West",
    value: "Lake Almanor West"
  },
  { key: "Lake Arrowhead", text: "Lake Arrowhead", value: "Lake Arrowhead" },
  { key: "Lake Davis", text: "Lake Davis", value: "Lake Davis" },
  { key: "Lake Elsinore", text: "Lake Elsinore", value: "Lake Elsinore" },
  { key: "Lake Forest", text: "Lake Forest", value: "Lake Forest" },
  {
    key: "Lakehead-Lakeshore",
    text: "Lakehead-Lakeshore",
    value: "Lakehead-Lakeshore"
  },
  { key: "Lake Isabella", text: "Lake Isabella", value: "Lake Isabella" },
  {
    key: "Lakeland Village",
    text: "Lakeland Village",
    value: "Lakeland Village"
  },
  {
    key: "Lake Los Angeles",
    text: "Lake Los Angeles",
    value: "Lake Los Angeles"
  },
  { key: "Lake Nacimiento", text: "Lake Nacimiento", value: "Lake Nacimiento" },
  {
    key: "Lake of the Pines",
    text: "Lake of the Pines",
    value: "Lake of the Pines"
  },
  {
    key: "Lake of the Woods",
    text: "Lake of the Woods",
    value: "Lake of the Woods"
  },
  { key: "Lakeport", text: "Lakeport", value: "Lakeport" },
  { key: "Lake San Marcos", text: "Lake San Marcos", value: "Lake San Marcos" },
  { key: "Lakeside", text: "Lakeside", value: "Lakeside" },
  { key: "Lakeview", text: "Lakeview", value: "Lakeview" },
  { key: "Lake Wildwood", text: "Lake Wildwood", value: "Lake Wildwood" },
  { key: "Lakewood", text: "Lakewood", value: "Lakewood" },
  { key: "La Mesa", text: "La Mesa", value: "La Mesa" },
  { key: "La Mirada", text: "La Mirada", value: "La Mirada" },
  { key: "Lamont", text: "Lamont", value: "Lamont" },
  { key: "Lanare", text: "Lanare", value: "Lanare" },
  { key: "Lancaster", text: "Lancaster", value: "Lancaster" },
  { key: "La Palma", text: "La Palma", value: "La Palma" },
  { key: "La Porte", text: "La Porte", value: "La Porte" },
  { key: "La Presa", text: "La Presa", value: "La Presa" },
  { key: "La Puente", text: "La Puente", value: "La Puente" },
  { key: "La Quinta", text: "La Quinta", value: "La Quinta" },
  { key: "La Riviera", text: "La Riviera", value: "La Riviera" },
  {
    key: "Larkfield-Wikiup",
    text: "Larkfield-Wikiup",
    value: "Larkfield-Wikiup"
  },
  { key: "Larkspur", text: "Larkspur", value: "Larkspur" },
  { key: "Las Flores", text: "Las Flores", value: "Las Flores" },
  { key: "Las Lomas", text: "Las Lomas", value: "Las Lomas" },
  { key: "Lathrop", text: "Lathrop", value: "Lathrop" },
  { key: "Laton", text: "Laton", value: "Laton" },
  { key: "La Verne", text: "La Verne", value: "La Verne" },
  { key: "Lawndale", text: "Lawndale", value: "Lawndale" },
  { key: "Laytonville", text: "Laytonville", value: "Laytonville" },
  { key: "Lebec", text: "Lebec", value: "Lebec" },
  { key: "Le Grand", text: "Le Grand", value: "Le Grand" },
  { key: "Lemon Cove", text: "Lemon Cove", value: "Lemon Cove" },
  { key: "Lemon Grove", text: "Lemon Grove", value: "Lemon Grove" },
  { key: "Lemoore", text: "Lemoore", value: "Lemoore" },
  { key: "Lemoore Station", text: "Lemoore Station", value: "Lemoore Station" },
  { key: "Lennox", text: "Lennox", value: "Lennox" },
  { key: "Lenwood", text: "Lenwood", value: "Lenwood" },
  { key: "Lewiston", text: "Lewiston", value: "Lewiston" },
  { key: "Lexington Hills", text: "Lexington Hills", value: "Lexington Hills" },
  { key: "Lincoln", text: "Lincoln", value: "Lincoln" },
  { key: "Lincoln Village", text: "Lincoln Village", value: "Lincoln Village" },
  { key: "Linda", text: "Linda", value: "Linda" },
  { key: "Linden", text: "Linden", value: "Linden" },
  { key: "Lindsay", text: "Lindsay", value: "Lindsay" },
  {
    key: "Little Grass Valley",
    text: "Little Grass Valley",
    value: "Little Grass Valley"
  },
  { key: "Littlerock", text: "Littlerock", value: "Littlerock" },
  { key: "Live Oak", text: "Live Oak", value: "Live Oak" },
  { key: "Livermore", text: "Livermore", value: "Livermore" },
  { key: "Livingston", text: "Livingston", value: "Livingston" },
  { key: "Lockeford", text: "Lockeford", value: "Lockeford" },
  { key: "Lodi", text: "Lodi", value: "Lodi" },
  { key: "Loma Linda", text: "Loma Linda", value: "Loma Linda" },
  { key: "Loma Rica", text: "Loma Rica", value: "Loma Rica" },
  { key: "Lomita", text: "Lomita", value: "Lomita" },
  { key: "Lompoc", text: "Lompoc", value: "Lompoc" },
  { key: "London", text: "London", value: "London" },
  { key: "Lone Pine", text: "Lone Pine", value: "Lone Pine" },
  { key: "Long Beach", text: "Long Beach", value: "Long Beach" },
  { key: "Loomis", text: "Loomis", value: "Loomis" },
  { key: "Los Alamitos", text: "Los Alamitos", value: "Los Alamitos" },
  { key: "Los Alamos", text: "Los Alamos", value: "Los Alamos" },
  { key: "Los Altos", text: "Los Altos", value: "Los Altos" },
  { key: "Los Altos Hills", text: "Los Altos Hills", value: "Los Altos Hills" },
  { key: "Los Angeles", text: "Los Angeles", value: "Los Angeles" },
  { key: "Los Banos", text: "Los Banos", value: "Los Banos" },
  { key: "Los Gatos", text: "Los Gatos", value: "Los Gatos" },
  { key: "Los Molinos", text: "Los Molinos", value: "Los Molinos" },
  { key: "Lost Hills", text: "Lost Hills", value: "Lost Hills" },
  { key: "Lower Lake", text: "Lower Lake", value: "Lower Lake" },
  { key: "Loyalton", text: "Loyalton", value: "Loyalton" },
  { key: "Loyola", text: "Loyola", value: "Loyola" },
  {
    key: "Lucas Valley-Marinwood",
    text: "Lucas Valley-Marinwood",
    value: "Lucas Valley-Marinwood"
  },
  { key: "Lucerne", text: "Lucerne", value: "Lucerne" },
  { key: "Lynwood", text: "Lynwood", value: "Lynwood" },
  { key: "McArthur", text: "McArthur", value: "McArthur" },
  { key: "McCloud", text: "McCloud", value: "McCloud" },
  { key: "Macdoel", text: "Macdoel", value: "Macdoel" },
  { key: "McFarland", text: "McFarland", value: "McFarland" },
  { key: "McKinleyville", text: "McKinleyville", value: "McKinleyville" },
  { key: "McKittrick", text: "McKittrick", value: "McKittrick" },
  { key: "Madera", text: "Madera", value: "Madera" },
  { key: "Madera Acres", text: "Madera Acres", value: "Madera Acres" },
  { key: "Magalia", text: "Magalia", value: "Magalia" },
  { key: "Malibu", text: "Malibu", value: "Malibu" },
  { key: "Mammoth Lakes", text: "Mammoth Lakes", value: "Mammoth Lakes" },
  { key: "Manhattan Beach", text: "Manhattan Beach", value: "Manhattan Beach" },
  { key: "Manteca", text: "Manteca", value: "Manteca" },
  { key: "Manton", text: "Manton", value: "Manton" },
  { key: "March AFB", text: "March AFB", value: "March AFB" },
  { key: "Maricopa", text: "Maricopa", value: "Maricopa" },
  { key: "Marina", text: "Marina", value: "Marina" },
  { key: "Marina del Rey", text: "Marina del Rey", value: "Marina del Rey" },
  { key: "Mariposa", text: "Mariposa", value: "Mariposa" },
  { key: "Markleeville", text: "Markleeville", value: "Markleeville" },
  { key: "Martinez", text: "Martinez", value: "Martinez" },
  { key: "Marysville", text: "Marysville", value: "Marysville" },
  {
    key: "Mayflower Village",
    text: "Mayflower Village",
    value: "Mayflower Village"
  },
  { key: "Maywood", text: "Maywood", value: "Maywood" },
  { key: "Meadow Valley", text: "Meadow Valley", value: "Meadow Valley" },
  { key: "Meadow Vista", text: "Meadow Vista", value: "Meadow Vista" },
  { key: "Mecca", text: "Mecca", value: "Mecca" },
  { key: "Meiners Oaks", text: "Meiners Oaks", value: "Meiners Oaks" },
  { key: "Mendocino", text: "Mendocino", value: "Mendocino" },
  { key: "Mendota", text: "Mendota", value: "Mendota" },
  { key: "Menlo Park", text: "Menlo Park", value: "Menlo Park" },
  { key: "Mentone", text: "Mentone", value: "Mentone" },
  { key: "Merced", text: "Merced", value: "Merced" },
  { key: "Mesa", text: "Mesa", value: "Mesa" },
  { key: "Mesa Vista", text: "Mesa Vista", value: "Mesa Vista" },
  { key: "Mettler", text: "Mettler", value: "Mettler" },
  { key: "Middletown", text: "Middletown", value: "Middletown" },
  { key: "Millbrae", text: "Millbrae", value: "Millbrae" },
  { key: "Mill Valley", text: "Mill Valley", value: "Mill Valley" },
  { key: "Millville", text: "Millville", value: "Millville" },
  { key: "Milpitas", text: "Milpitas", value: "Milpitas" },
  { key: "Mineral", text: "Mineral", value: "Mineral" },
  { key: "Mira Loma", text: "Mira Loma", value: "Mira Loma" },
  { key: "Mira Monte", text: "Mira Monte", value: "Mira Monte" },
  { key: "Mission Canyon", text: "Mission Canyon", value: "Mission Canyon" },
  { key: "Mission Hills", text: "Mission Hills", value: "Mission Hills" },
  { key: "Mission Viejo", text: "Mission Viejo", value: "Mission Viejo" },
  { key: "Mi-Wuk Village", text: "Mi-Wuk Village", value: "Mi-Wuk Village" },
  { text: "Modesto", value: "Modesto" },
  { key: "Mohawk Vista", text: "Mohawk Vista", value: "Mohawk Vista" },
  { key: "Mojave", text: "Mojave", value: "Mojave" },
  { key: "Mokelumne Hill", text: "Mokelumne Hill", value: "Mokelumne Hill" },
  { key: "Mono Vista", text: "Mono Vista", value: "Mono Vista" },
  { key: "Monrovia", text: "Monrovia", value: "Monrovia" },
  { key: "Montague", text: "Montague", value: "Montague" },
  { key: "Montara", text: "Montara", value: "Montara" },
  { key: "Montclair", text: "Montclair", value: "Montclair" },
  { key: "Montebello", text: "Montebello", value: "Montebello" },
  { key: "Montecito", text: "Montecito", value: "Montecito" },
  { key: "Monterey", text: "Monterey", value: "Monterey" },
  { key: "Monterey Park", text: "Monterey Park", value: "Monterey Park" },
  { key: "Monte Rio", text: "Monte Rio", value: "Monte Rio" },
  { key: "Monte Sereno", text: "Monte Sereno", value: "Monte Sereno" },
  {
    key: "Montgomery Creek",
    text: "Montgomery Creek",
    value: "Montgomery Creek"
  },
  { key: "Moorpark", text: "Moorpark", value: "Moorpark" },
  { key: "Morada", text: "Morada", value: "Morada" },
  { key: "Moraga", text: "Moraga", value: "Moraga" },
  { key: "Moreno Valley", text: "Moreno Valley", value: "Moreno Valley" },
  { key: "Morgan Hill", text: "Morgan Hill", value: "Morgan Hill" },
  { key: "Morongo Valley", text: "Morongo Valley", value: "Morongo Valley" },
  { key: "Morro Bay", text: "Morro Bay", value: "Morro Bay" },
  { key: "Moss Beach", text: "Moss Beach", value: "Moss Beach" },
  { key: "Moss Landing", text: "Moss Landing", value: "Moss Landing" },
  { key: "Mountain Mesa", text: "Mountain Mesa", value: "Mountain Mesa" },
  { key: "Mountain Ranch", text: "Mountain Ranch", value: "Mountain Ranch" },
  { key: "Mountain View", text: "Mountain View", value: "Mountain View" },
  {
    key: "Mountain View Acres",
    text: "Mountain View Acres",
    value: "Mountain View Acres"
  },
  { key: "Mount Hebron", text: "Mount Hebron", value: "Mount Hebron" },
  { key: "Mount Shasta", text: "Mount Shasta", value: "Mount Shasta" },
  { key: "Muir Beach", text: "Muir Beach", value: "Muir Beach" },
  { key: "Murphys", text: "Murphys", value: "Murphys" },
  { key: "Murrieta", text: "Murrieta", value: "Murrieta" },
  {
    key: "Murrieta Hot Springs",
    text: "Murrieta Hot Springs",
    value: "Murrieta Hot Springs"
  },
  { key: "Muscoy", text: "Muscoy", value: "Muscoy" },
  { key: "Myrtletown", text: "Myrtletown", value: "Myrtletown" },
  { key: "Napa", text: "Napa", value: "Napa" },
  { key: "National City", text: "National City", value: "National City" },
  { key: "Nebo Center", text: "Nebo Center", value: "Nebo Center" },
  { key: "Needles", text: "Needles", value: "Needles" },
  { key: "Nevada City", text: "Nevada City", value: "Nevada City" },
  { key: "Newark", text: "Newark", value: "Newark" },
  { key: "Newman", text: "Newman", value: "Newman" },
  { key: "Newport Beach", text: "Newport Beach", value: "Newport Beach" },
  { key: "Newport Coast", text: "Newport Coast", value: "Newport Coast" },
  { key: "Nice", text: "Nice", value: "Nice" },
  { key: "Niland", text: "Niland", value: "Niland" },
  { key: "Nipomo", text: "Nipomo", value: "Nipomo" },
  { key: "Norco", text: "Norco", value: "Norco" },
  { key: "North Auburn", text: "North Auburn", value: "North Auburn" },
  { key: "North Edwards", text: "North Edwards", value: "North Edwards" },
  { key: "North El Monte", text: "North El Monte", value: "North El Monte" },
  { key: "North Fair Oaks", text: "North Fair Oaks", value: "North Fair Oaks" },
  { key: "North Highlands", text: "North Highlands", value: "North Highlands" },
  { key: "North Lakeport", text: "North Lakeport", value: "North Lakeport" },
  {
    key: "North Woodbridge",
    text: "North Woodbridge",
    value: "North Woodbridge"
  },
  { key: "Norwalk", text: "Norwalk", value: "Norwalk" },
  { key: "Novato", text: "Novato", value: "Novato" },
  { key: "Nuevo", text: "Nuevo", value: "Nuevo" },
  { key: "Oakdale", text: "Oakdale", value: "Oakdale" },
  { key: "Oakhurst", text: "Oakhurst", value: "Oakhurst" },
  { key: "Oakland", text: "Oakland", value: "Oakland" },
  { key: "Oakley", text: "Oakley", value: "Oakley" },
  { key: "Oak Park", text: "Oak Park", value: "Oak Park" },
  { key: "Oak View", text: "Oak View", value: "Oak View" },
  { key: "Occidental", text: "Occidental", value: "Occidental" },
  { key: "Oceano", text: "Oceano", value: "Oceano" },
  { key: "Oceanside", text: "Oceanside", value: "Oceanside" },
  { key: "Ocotillo", text: "Ocotillo", value: "Ocotillo" },
  { key: "Oildale", text: "Oildale", value: "Oildale" },
  { key: "Ojai", text: "Ojai", value: "Ojai" },
  { key: "Olancha", text: "Olancha", value: "Olancha" },
  { key: "Olivehurst", text: "Olivehurst", value: "Olivehurst" },
  { key: "Ontario", text: "Ontario", value: "Ontario" },
  { key: "Onyx", text: "Onyx", value: "Onyx" },
  { key: "Opal Cliffs", text: "Opal Cliffs", value: "Opal Cliffs" },
  { key: "Orange", text: "Orange", value: "Orange" },
  { key: "Orange Cove", text: "Orange Cove", value: "Orange Cove" },
  { key: "Orangevale", text: "Orangevale", value: "Orangevale" },
  { key: "Orcutt", text: "Orcutt", value: "Orcutt" },
  { key: "Orinda", text: "Orinda", value: "Orinda" },
  { key: "Orland", text: "Orland", value: "Orland" },
  { key: "Orosi", text: "Orosi", value: "Orosi" },
  { key: "Oroville", text: "Oroville", value: "Oroville" },
  { key: "Oroville East", text: "Oroville East", value: "Oroville East" },
  { key: "Oxnard", text: "Oxnard", value: "Oxnard" },
  { key: "Pacheco", text: "Pacheco", value: "Pacheco" },
  { key: "Pacifica", text: "Pacifica", value: "Pacifica" },
  { key: "Pacific Grove", text: "Pacific Grove", value: "Pacific Grove" },
  { key: "Pajaro", text: "Pajaro", value: "Pajaro" },
  { key: "Palermo", text: "Palermo", value: "Palermo" },
  { key: "Palmdale", text: "Palmdale", value: "Palmdale" },
  { key: "Palm Desert", text: "Palm Desert", value: "Palm Desert" },
  { key: "Palm Springs", text: "Palm Springs", value: "Palm Springs" },
  { key: "Palo Alto", text: "Palo Alto", value: "Palo Alto" },
  { key: "Palo Cedro", text: "Palo Cedro", value: "Palo Cedro" },
  {
    key: "Palos Verdes Estates",
    text: "Palos Verdes Estates",
    value: "Palos Verdes Estates"
  },
  { key: "Palo Verde", text: "Palo Verde", value: "Palo Verde" },
  { key: "Paradise", text: "Paradise", value: "Paradise" },
  { key: "Paramount", text: "Paramount", value: "Paramount" },
  { key: "Parksdale", text: "Parksdale", value: "Parksdale" },
  {
    key: "Parkway-South Sacramento",
    text: "Parkway-South Sacramento",
    value: "Parkway-South Sacramento"
  },
  { key: "Parkwood", text: "Parkwood", value: "Parkwood" },
  { key: "Parlier", text: "Parlier", value: "Parlier" },
  { key: "Pasadena", text: "Pasadena", value: "Pasadena" },
  { key: "Patterson", text: "Patterson", value: "Patterson" },
  { key: "Paxton", text: "Paxton", value: "Paxton" },
  { key: "Pearsonville", text: "Pearsonville", value: "Pearsonville" },
  { key: "Pedley", text: "Pedley", value: "Pedley" },
  { key: "Penn Valley", text: "Penn Valley", value: "Penn Valley" },
  { key: "Perris", text: "Perris", value: "Perris" },
  { key: "Petaluma", text: "Petaluma", value: "Petaluma" },
  {
    key: "Phoenix Lake-Cedar Ridge",
    text: "Phoenix Lake-Cedar Ridge",
    value: "Phoenix Lake-Cedar Ridge"
  },
  { key: "Pico Rivera", text: "Pico Rivera", value: "Pico Rivera" },
  { key: "Piedmont", text: "Piedmont", value: "Piedmont" },
  { key: "Pine Hills", text: "Pine Hills", value: "Pine Hills" },
  {
    key: "Pine Mountain Club",
    text: "Pine Mountain Club",
    value: "Pine Mountain Club"
  },
  { key: "Pine Valley", text: "Pine Valley", value: "Pine Valley" },
  { key: "Pinole", text: "Pinole", value: "Pinole" },
  { key: "Piru", text: "Piru", value: "Piru" },
  { key: "Pismo Beach", text: "Pismo Beach", value: "Pismo Beach" },
  { key: "Pittsburg", text: "Pittsburg", value: "Pittsburg" },
  { key: "Pixley", text: "Pixley", value: "Pixley" },
  { key: "Placentia", text: "Placentia", value: "Placentia" },
  { key: "Placerville", text: "Placerville", value: "Placerville" },
  { key: "Planada", text: "Planada", value: "Planada" },
  { key: "Pleasant Hill", text: "Pleasant Hill", value: "Pleasant Hill" },
  { key: "Pleasanton", text: "Pleasanton", value: "Pleasanton" },
  { key: "Plumas Eureka", text: "Plumas Eureka", value: "Plumas Eureka" },
  { key: "Plymouth", text: "Plymouth", value: "Plymouth" },
  { key: "Point Arena", text: "Point Arena", value: "Point Arena" },
  {
    key: "Point Reyes Station",
    text: "Point Reyes Station",
    value: "Point Reyes Station"
  },
  { key: "Pollock Pines", text: "Pollock Pines", value: "Pollock Pines" },
  { key: "Pomona", text: "Pomona", value: "Pomona" },
  {
    key: "Poplar-Cotton Center",
    text: "Poplar-Cotton Center",
    value: "Poplar-Cotton Center"
  },
  { key: "Port Costa", text: "Port Costa", value: "Port Costa" },
  { key: "Porterville", text: "Porterville", value: "Porterville" },
  { key: "Port Hueneme", text: "Port Hueneme", value: "Port Hueneme" },
  { key: "Portola", text: "Portola", value: "Portola" },
  { key: "Portola Hills", text: "Portola Hills", value: "Portola Hills" },
  { key: "Portola Valley", text: "Portola Valley", value: "Portola Valley" },
  { key: "Poway", text: "Poway", value: "Poway" },
  { key: "Prattville", text: "Prattville", value: "Prattville" },
  { key: "Prunedale", text: "Prunedale", value: "Prunedale" },
  { key: "Quail Valley", text: "Quail Valley", value: "Quail Valley" },
  { key: "Quartz Hill", text: "Quartz Hill", value: "Quartz Hill" },
  { key: "Quincy", text: "Quincy", value: "Quincy" },
  { key: "Rail Road Flat", text: "Rail Road Flat", value: "Rail Road Flat" },
  { key: "Rainbow", text: "Rainbow", value: "Rainbow" },
  { key: "Raisin City", text: "Raisin City", value: "Raisin City" },
  { key: "Ramona", text: "Ramona", value: "Ramona" },
  {
    key: "Rancho Calaveras",
    text: "Rancho Calaveras",
    value: "Rancho Calaveras"
  },
  { key: "Rancho Cordova", text: "Rancho Cordova", value: "Rancho Cordova" },
  {
    key: "Rancho Cucamonga",
    text: "Rancho Cucamonga",
    value: "Rancho Cucamonga"
  },
  { key: "Rancho Mirage", text: "Rancho Mirage", value: "Rancho Mirage" },
  { key: "Rancho Murieta", text: "Rancho Murieta", value: "Rancho Murieta" },
  {
    key: "Rancho Palos Verdes",
    text: "Rancho Palos Verdes",
    value: "Rancho Palos Verdes"
  },
  {
    key: "Rancho San Diego",
    text: "Rancho San Diego",
    value: "Rancho San Diego"
  },
  { key: "Rancho Santa Fe", text: "Rancho Santa Fe", value: "Rancho Santa Fe" },
  {
    key: "Rancho Santa Margarita",
    text: "Rancho Santa Margarita",
    value: "Rancho Santa Margarita"
  },
  {
    key: "Rancho Tehama Reserve",
    text: "Rancho Tehama Reserve",
    value: "Rancho Tehama Reserve"
  },
  { key: "Randsburg", text: "Randsburg", value: "Randsburg" },
  { key: "Red Bluff", text: "Red Bluff", value: "Red Bluff" },
  { key: "Redding", text: "Redding", value: "Redding" },
  { key: "Redlands", text: "Redlands", value: "Redlands" },
  { key: "Redondo Beach", text: "Redondo Beach", value: "Redondo Beach" },
  { key: "Redway", text: "Redway", value: "Redway" },
  { key: "Redwood City", text: "Redwood City", value: "Redwood City" },
  { key: "Reedley", text: "Reedley", value: "Reedley" },
  { key: "Rialto", text: "Rialto", value: "Rialto" },
  { key: "Richgrove", text: "Richgrove", value: "Richgrove" },
  { key: "Richmond", text: "Richmond", value: "Richmond" },
  { key: "Ridgecrest", text: "Ridgecrest", value: "Ridgecrest" },
  { key: "Ridgemark", text: "Ridgemark", value: "Ridgemark" },
  { key: "Rio Dell", text: "Rio Dell", value: "Rio Dell" },
  { key: "Rio del Mar", text: "Rio del Mar", value: "Rio del Mar" },
  { key: "Rio Linda", text: "Rio Linda", value: "Rio Linda" },
  { key: "Rio Vista", text: "Rio Vista", value: "Rio Vista" },
  { key: "Ripon", text: "Ripon", value: "Ripon" },
  { key: "Riverbank", text: "Riverbank", value: "Riverbank" },
  { key: "Riverdale", text: "Riverdale", value: "Riverdale" },
  { key: "Riverdale Park", text: "Riverdale Park", value: "Riverdale Park" },
  { key: "Riverside", text: "Riverside", value: "Riverside" },
  { key: "Rocklin", text: "Rocklin", value: "Rocklin" },
  { key: "Rodeo", text: "Rodeo", value: "Rodeo" },
  { key: "Rohnert Park", text: "Rohnert Park", value: "Rohnert Park" },
  { key: "Rolling Hills", text: "Rolling Hills", value: "Rolling Hills" },
  {
    key: "Rolling Hills Estates",
    text: "Rolling Hills Estates",
    value: "Rolling Hills Estates"
  },
  { key: "Rollingwood", text: "Rollingwood", value: "Rollingwood" },
  { key: "Romoland", text: "Romoland", value: "Romoland" },
  { key: "Rosamond", text: "Rosamond", value: "Rosamond" },
  { key: "Rosedale", text: "Rosedale", value: "Rosedale" },
  { key: "Roseland", text: "Roseland", value: "Roseland" },
  { key: "Rosemead", text: "Rosemead", value: "Rosemead" },
  { key: "Rosemont", text: "Rosemont", value: "Rosemont" },
  { key: "Roseville", text: "Roseville", value: "Roseville" },
  { key: "Ross", text: "Ross", value: "Ross" },
  { key: "Rossmoor", text: "Rossmoor", value: "Rossmoor" },
  { key: "Round Mountain", text: "Round Mountain", value: "Round Mountain" },
  { key: "Round Valley", text: "Round Valley", value: "Round Valley" },
  { key: "Rowland Heights", text: "Rowland Heights", value: "Rowland Heights" },
  { key: "Rubidoux", text: "Rubidoux", value: "Rubidoux" },
  { key: "Running Springs", text: "Running Springs", value: "Running Springs" },
  { key: "Sacramento", text: "Sacramento", value: "Sacramento" },
  { key: "St. Helena", text: "St. Helena", value: "St. Helena" },
  { key: "Salida", text: "Salida", value: "Salida" },
  { key: "Salinas", text: "Salinas", value: "Salinas" },
  { key: "Salton City", text: "Salton City", value: "Salton City" },
  {
    key: "Salton Sea Beach",
    text: "Salton Sea Beach",
    value: "Salton Sea Beach"
  },
  { key: "San Andreas", text: "San Andreas", value: "San Andreas" },
  { key: "San Anselmo", text: "San Anselmo", value: "San Anselmo" },
  {
    key: "San Antonio Heights",
    text: "San Antonio Heights",
    value: "San Antonio Heights"
  },
  { key: "San Ardo", text: "San Ardo", value: "San Ardo" },
  { key: "San Bernardino", text: "San Bernardino", value: "San Bernardino" },
  { key: "San Bruno", text: "San Bruno", value: "San Bruno" },
  {
    key: "San Buenaventura (Ventura)",
    text: "San Buenaventura (Ventura)",
    value: "San Buenaventura (Ventura)"
  },
  { key: "San Carlos", text: "San Carlos", value: "San Carlos" },
  { key: "San Clemente", text: "San Clemente", value: "San Clemente" },
  { key: "Sand City", text: "Sand City", value: "Sand City" },
  { key: "San Diego", text: "San Diego", value: "San Diego" },
  {
    key: "San Diego Country Estates",
    text: "San Diego Country Estates",
    value: "San Diego Country Estates"
  },
  { key: "San Dimas", text: "San Dimas", value: "San Dimas" },
  { key: "San Fernando", text: "San Fernando", value: "San Fernando" },
  { key: "San Francisco", text: "San Francisco", value: "San Francisco" },
  { key: "San Gabriel", text: "San Gabriel", value: "San Gabriel" },
  { key: "Sanger", text: "Sanger", value: "Sanger" },
  { key: "San Geronimo", text: "San Geronimo", value: "San Geronimo" },
  { key: "San Jacinto", text: "San Jacinto", value: "San Jacinto" },
  { key: "San Joaquin", text: "San Joaquin", value: "San Joaquin" },
  {
    key: "San Joaquin Hills",
    text: "San Joaquin Hills",
    value: "San Joaquin Hills"
  },
  { key: "San Jose", text: "San Jose", value: "San Jose" },
  {
    key: "San Juan Bautista",
    text: "San Juan Bautista",
    value: "San Juan Bautista"
  },
  {
    key: "San Juan Capistrano",
    text: "San Juan Capistrano",
    value: "San Juan Capistrano"
  },
  { key: "San Leandro", text: "San Leandro", value: "San Leandro" },
  { key: "San Lorenzo", text: "San Lorenzo", value: "San Lorenzo" },
  { key: "San Lucas", text: "San Lucas", value: "San Lucas" },
  { key: "San Luis Obispo", text: "San Luis Obispo", value: "San Luis Obispo" },
  { key: "San Marcos", text: "San Marcos", value: "San Marcos" },
  { key: "San Marino", text: "San Marino", value: "San Marino" },
  { key: "San Martin", text: "San Martin", value: "San Martin" },
  { key: "San Mateo", text: "San Mateo", value: "San Mateo" },
  { key: "San Miguel", text: "San Miguel", value: "San Miguel" },
  { key: "San Pablo", text: "San Pablo", value: "San Pablo" },
  { key: "San Rafael", text: "San Rafael", value: "San Rafael" },
  { key: "San Ramon", text: "San Ramon", value: "San Ramon" },
  { key: "Santa Ana", text: "Santa Ana", value: "Santa Ana" },
  { key: "Santa Barbara", text: "Santa Barbara", value: "Santa Barbara" },
  { key: "Santa Clara", text: "Santa Clara", value: "Santa Clara" },
  { key: "Santa Clarita", text: "Santa Clarita", value: "Santa Clarita" },
  { key: "Santa Cruz", text: "Santa Cruz", value: "Santa Cruz" },
  {
    key: "Santa Fe Springs",
    text: "Santa Fe Springs",
    value: "Santa Fe Springs"
  },
  { key: "Santa Maria", text: "Santa Maria", value: "Santa Maria" },
  { key: "Santa Monica", text: "Santa Monica", value: "Santa Monica" },
  { key: "Santa Paula", text: "Santa Paula", value: "Santa Paula" },
  { key: "Santa Rosa", text: "Santa Rosa", value: "Santa Rosa" },
  { key: "Santa Venetia", text: "Santa Venetia", value: "Santa Venetia" },
  { key: "Santa Ynez", text: "Santa Ynez", value: "Santa Ynez" },
  { key: "Santee", text: "Santee", value: "Santee" },
  { key: "Saratoga", text: "Saratoga", value: "Saratoga" },
  { key: "Sausalito", text: "Sausalito", value: "Sausalito" },
  { key: "Scotts Valley", text: "Scotts Valley", value: "Scotts Valley" },
  { key: "Seal Beach", text: "Seal Beach", value: "Seal Beach" },
  { key: "Searles Valley", text: "Searles Valley", value: "Searles Valley" },
  { key: "Seaside", text: "Seaside", value: "Seaside" },
  { key: "Sebastopol", text: "Sebastopol", value: "Sebastopol" },
  { key: "Sedco Hills", text: "Sedco Hills", value: "Sedco Hills" },
  { key: "Seeley", text: "Seeley", value: "Seeley" },
  { key: "Selma", text: "Selma", value: "Selma" },
  { key: "Seven Trees", text: "Seven Trees", value: "Seven Trees" },
  { key: "Shackelford", text: "Shackelford", value: "Shackelford" },
  { key: "Shafter", text: "Shafter", value: "Shafter" },
  { key: "Shandon", text: "Shandon", value: "Shandon" },
  { key: "Shasta Lake", text: "Shasta Lake", value: "Shasta Lake" },
  { key: "Shaver Lake", text: "Shaver Lake", value: "Shaver Lake" },
  { key: "Shingle Springs", text: "Shingle Springs", value: "Shingle Springs" },
  { key: "Shingletown", text: "Shingletown", value: "Shingletown" },
  { key: "Shoshone", text: "Shoshone", value: "Shoshone" },
  { key: "Sierra Madre", text: "Sierra Madre", value: "Sierra Madre" },
  { key: "Signal Hill", text: "Signal Hill", value: "Signal Hill" },
  { key: "Simi Valley", text: "Simi Valley", value: "Simi Valley" },
  { key: "Solana Beach", text: "Solana Beach", value: "Solana Beach" },
  { key: "Soledad", text: "Soledad", value: "Soledad" },
  { key: "Solvang", text: "Solvang", value: "Solvang" },
  { key: "Sonoma", text: "Sonoma", value: "Sonoma" },
  { key: "Sonora", text: "Sonora", value: "Sonora" },
  { key: "Soquel", text: "Soquel", value: "Soquel" },
  { key: "Soulsbyville", text: "Soulsbyville", value: "Soulsbyville" },
  { key: "South Dos Palos", text: "South Dos Palos", value: "South Dos Palos" },
  { key: "South El Monte", text: "South El Monte", value: "South El Monte" },
  { key: "South Gate", text: "South Gate", value: "South Gate" },
  {
    key: "South Lake Tahoe",
    text: "South Lake Tahoe",
    value: "South Lake Tahoe"
  },
  { key: "South Oroville", text: "South Oroville", value: "South Oroville" },
  { key: "South Pasadena", text: "South Pasadena", value: "South Pasadena" },
  {
    key: "South San Francisco",
    text: "South San Francisco",
    value: "South San Francisco"
  },
  {
    key: "South San Gabriel",
    text: "South San Gabriel",
    value: "South San Gabriel"
  },
  {
    key: "South San Jose Hills",
    text: "South San Jose Hills",
    value: "South San Jose Hills"
  },
  { key: "South Taft", text: "South Taft", value: "South Taft" },
  { key: "South Whittier", text: "South Whittier", value: "South Whittier" },
  {
    key: "South Woodbridge",
    text: "South Woodbridge",
    value: "South Woodbridge"
  },
  { key: "South Yuba City", text: "South Yuba City", value: "South Yuba City" },
  { key: "Spreckels", text: "Spreckels", value: "Spreckels" },
  { key: "Spring Garden", text: "Spring Garden", value: "Spring Garden" },
  { key: "Spring Valley", text: "Spring Valley", value: "Spring Valley" },
  { key: "Springville", text: "Springville", value: "Springville" },
  { key: "Squaw Valley", text: "Squaw Valley", value: "Squaw Valley" },
  {
    key: "Squirrel Mountain Valley",
    text: "Squirrel Mountain Valley",
    value: "Squirrel Mountain Valley"
  },
  {
    key: "Stallion Springs",
    text: "Stallion Springs",
    value: "Stallion Springs"
  },
  { key: "Stanford", text: "Stanford", value: "Stanford" },
  { key: "Stanton", text: "Stanton", value: "Stanton" },
  { key: "Stinson Beach", text: "Stinson Beach", value: "Stinson Beach" },
  { key: "Stockton", text: "Stockton", value: "Stockton" },
  { key: "Storrie", text: "Storrie", value: "Storrie" },
  { key: "Stratford", text: "Stratford", value: "Stratford" },
  { key: "Strathmore", text: "Strathmore", value: "Strathmore" },
  { key: "Strawberry", text: "Strawberry", value: "Strawberry" },
  { key: "Suisun City", text: "Suisun City", value: "Suisun City" },
  { key: "Summerland", text: "Summerland", value: "Summerland" },
  { key: "Sun City", text: "Sun City", value: "Sun City" },
  {
    key: "Sunnyside-Tahoe City",
    text: "Sunnyside-Tahoe City",
    value: "Sunnyside-Tahoe City"
  },
  { key: "Sunnyslope", text: "Sunnyslope", value: "Sunnyslope" },
  { key: "Sunnyvale", text: "Sunnyvale", value: "Sunnyvale" },
  { key: "Sunol", text: "Sunol", value: "Sunol" },
  { key: "Sunol-Midtown", text: "Sunol-Midtown", value: "Sunol-Midtown" },
  { key: "Susanville", text: "Susanville", value: "Susanville" },
  { key: "Sutter", text: "Sutter", value: "Sutter" },
  { key: "Sutter Creek", text: "Sutter Creek", value: "Sutter Creek" },
  { key: "Taft", text: "Taft", value: "Taft" },
  { key: "Taft Heights", text: "Taft Heights", value: "Taft Heights" },
  { key: "Taft Mosswood", text: "Taft Mosswood", value: "Taft Mosswood" },
  { key: "Tahoe Vista", text: "Tahoe Vista", value: "Tahoe Vista" },
  { key: "Talmage", text: "Talmage", value: "Talmage" },
  {
    key: "Tamalpais-Homestead Valley",
    text: "Tamalpais-Homestead Valley",
    value: "Tamalpais-Homestead Valley"
  },
  { key: "Tara Hills", text: "Tara Hills", value: "Tara Hills" },
  { key: "Taylorsville", text: "Taylorsville", value: "Taylorsville" },
  { key: "Tecopa", text: "Tecopa", value: "Tecopa" },
  { key: "Tehachapi", text: "Tehachapi", value: "Tehachapi" },
  { key: "Tehama", text: "Tehama", value: "Tehama" },
  { key: "Temecula", text: "Temecula", value: "Temecula" },
  { key: "Temelec", text: "Temelec", value: "Temelec" },
  { key: "Temple City", text: "Temple City", value: "Temple City" },
  { key: "Templeton", text: "Templeton", value: "Templeton" },
  { key: "Tennant", text: "Tennant", value: "Tennant" },
  { key: "Terra Bella", text: "Terra Bella", value: "Terra Bella" },
  { key: "Thermalito", text: "Thermalito", value: "Thermalito" },
  { key: "Thousand Oaks", text: "Thousand Oaks", value: "Thousand Oaks" },
  { key: "Thousand Palms", text: "Thousand Palms", value: "Thousand Palms" },
  { key: "Three Rivers", text: "Three Rivers", value: "Three Rivers" },
  { key: "Tiburon", text: "Tiburon", value: "Tiburon" },
  { key: "Tierra Buena", text: "Tierra Buena", value: "Tierra Buena" },
  { key: "Tipton", text: "Tipton", value: "Tipton" },
  { key: "Tobin", text: "Tobin", value: "Tobin" },
  { key: "Tomales", text: "Tomales", value: "Tomales" },
  { key: "Toro Canyon", text: "Toro Canyon", value: "Toro Canyon" },
  { key: "Torrance", text: "Torrance", value: "Torrance" },
  { key: "Tracy", text: "Tracy", value: "Tracy" },
  { key: "Tranquillity", text: "Tranquillity", value: "Tranquillity" },
  { key: "Traver", text: "Traver", value: "Traver" },
  { key: "Trinidad", text: "Trinidad", value: "Trinidad" },
  { key: "Truckee", text: "Truckee", value: "Truckee" },
  { key: "Tulare", text: "Tulare", value: "Tulare" },
  { key: "Tulelake", text: "Tulelake", value: "Tulelake" },
  { key: "Tuolumne City", text: "Tuolumne City", value: "Tuolumne City" },
  { key: "Tupman", text: "Tupman", value: "Tupman" },
  { key: "Turlock", text: "Turlock", value: "Turlock" },
  { key: "Tustin", text: "Tustin", value: "Tustin" },
  {
    key: "Tustin Foothills",
    text: "Tustin Foothills",
    value: "Tustin Foothills"
  },
  { key: "Twain", text: "Twain", value: "Twain" },
  { key: "Twain Harte", text: "Twain Harte", value: "Twain Harte" },
  {
    key: "Twentynine Palms",
    text: "Twentynine Palms",
    value: "Twentynine Palms"
  },
  {
    key: "Twentynine Palms Base",
    text: "Twentynine Palms Base",
    value: "Twentynine Palms Base"
  },
  { key: "Twin Lakes", text: "Twin Lakes", value: "Twin Lakes" },
  { key: "Union City", text: "Union City", value: "Union City" },
  { key: "Upland", text: "Upland", value: "Upland" },
  { key: "Upper Lake", text: "Upper Lake", value: "Upper Lake" },
  { key: "Vacaville", text: "Vacaville", value: "Vacaville" },
  { key: "Valinda", text: "Valinda", value: "Valinda" },
  { key: "Vallecito", text: "Vallecito", value: "Vallecito" },
  { key: "Vallejo", text: "Vallejo", value: "Vallejo" },
  { key: "Valle Vista", text: "Valle Vista", value: "Valle Vista" },
  { key: "Valley Acres", text: "Valley Acres", value: "Valley Acres" },
  { key: "Valley Center", text: "Valley Center", value: "Valley Center" },
  { key: "Valley Ranch", text: "Valley Ranch", value: "Valley Ranch" },
  { key: "Valley Springs", text: "Valley Springs", value: "Valley Springs" },
  { key: "Val Verde", text: "Val Verde", value: "Val Verde" },
  { key: "Vandenberg AFB", text: "Vandenberg AFB", value: "Vandenberg AFB" },
  {
    key: "Vandenberg Village",
    text: "Vandenberg Village",
    value: "Vandenberg Village"
  },
  { key: "Vernon", text: "Vernon", value: "Vernon" },
  { key: "Victorville", text: "Victorville", value: "Victorville" },
  {
    key: "View Park-Windsor Hills",
    text: "View Park-Windsor Hills",
    value: "View Park-Windsor Hills"
  },
  { key: "Villa Park", text: "Villa Park", value: "Villa Park" },
  { key: "Vincent", text: "Vincent", value: "Vincent" },
  { key: "Vine Hill", text: "Vine Hill", value: "Vine Hill" },
  { key: "Vineyard", text: "Vineyard", value: "Vineyard" },
  { key: "Visalia", text: "Visalia", value: "Visalia" },
  { key: "Vista", text: "Vista", value: "Vista" },
  { key: "Waldon", text: "Waldon", value: "Waldon" },
  { key: "Wallace", text: "Wallace", value: "Wallace" },
  { key: "Walnut", text: "Walnut", value: "Walnut" },
  { key: "Walnut Creek", text: "Walnut Creek", value: "Walnut Creek" },
  { key: "Walnut Grove", text: "Walnut Grove", value: "Walnut Grove" },
  { key: "Walnut Park", text: "Walnut Park", value: "Walnut Park" },
  { key: "Wasco", text: "Wasco", value: "Wasco" },
  { key: "Waterford", text: "Waterford", value: "Waterford" },
  { key: "Watsonville", text: "Watsonville", value: "Watsonville" },
  { key: "Weaverville", text: "Weaverville", value: "Weaverville" },
  { key: "Weed", text: "Weed", value: "Weed" },
  { key: "Weedpatch", text: "Weedpatch", value: "Weedpatch" },
  { key: "Weldon", text: "Weldon", value: "Weldon" },
  { key: "West Athens", text: "West Athens", value: "West Athens" },
  { key: "West Bishop", text: "West Bishop", value: "West Bishop" },
  { key: "West Carson", text: "West Carson", value: "West Carson" },
  { key: "West Compton", text: "West Compton", value: "West Compton" },
  { key: "West Covina", text: "West Covina", value: "West Covina" },
  {
    key: "Westhaven-Moonstone",
    text: "Westhaven-Moonstone",
    value: "Westhaven-Moonstone"
  },
  { key: "West Hollywood", text: "West Hollywood", value: "West Hollywood" },
  {
    key: "Westlake Village",
    text: "Westlake Village",
    value: "Westlake Village"
  },
  { key: "Westley", text: "Westley", value: "Westley" },
  { key: "West Menlo Park", text: "West Menlo Park", value: "West Menlo Park" },
  { key: "Westminster", text: "Westminster", value: "Westminster" },
  { key: "West Modesto", text: "West Modesto", value: "West Modesto" },
  { key: "Westmont", text: "Westmont", value: "Westmont" },
  { key: "Westmorland", text: "Westmorland", value: "Westmorland" },
  { key: "West Point", text: "West Point", value: "West Point" },
  {
    key: "West Puente Valley",
    text: "West Puente Valley",
    value: "West Puente Valley"
  },
  { key: "West Sacramento", text: "West Sacramento", value: "West Sacramento" },
  {
    key: "West Whittier-Los Nietos",
    text: "West Whittier-Los Nietos",
    value: "West Whittier-Los Nietos"
  },
  { key: "Westwood", text: "Westwood", value: "Westwood" },
  { key: "Wheatland", text: "Wheatland", value: "Wheatland" },
  { key: "Whitehawk", text: "Whitehawk", value: "Whitehawk" },
  { key: "Whittier", text: "Whittier", value: "Whittier" },
  { key: "Wildomar", text: "Wildomar", value: "Wildomar" },
  { key: "Wilkerson", text: "Wilkerson", value: "Wilkerson" },
  { key: "Williams", text: "Williams", value: "Williams" },
  { key: "Willits", text: "Willits", value: "Willits" },
  { key: "Willowbrook", text: "Willowbrook", value: "Willowbrook" },
  { key: "Willow Creek", text: "Willow Creek", value: "Willow Creek" },
  { key: "Willows", text: "Willows", value: "Willows" },
  { key: "Wilton", text: "Wilton", value: "Wilton" },
  { key: "Winchester", text: "Winchester", value: "Winchester" },
  { key: "Windsor", text: "Windsor", value: "Windsor" },
  { key: "Winter Gardens", text: "Winter Gardens", value: "Winter Gardens" },
  { key: "Winterhaven", text: "Winterhaven", value: "Winterhaven" },
  { key: "Winters", text: "Winters", value: "Winters" },
  { key: "Winton", text: "Winton", value: "Winton" },
  { key: "Wofford Heights", text: "Wofford Heights", value: "Wofford Heights" },
  { key: "Woodacre", text: "Woodacre", value: "Woodacre" },
  { key: "Woodcrest", text: "Woodcrest", value: "Woodcrest" },
  { key: "Woodlake", text: "Woodlake", value: "Woodlake" },
  { key: "Woodland", text: "Woodland", value: "Woodland" },
  { key: "Woodside", text: "Woodside", value: "Woodside" },
  { key: "Woodville", text: "Woodville", value: "Woodville" },
  { key: "Wrightwood", text: "Wrightwood", value: "Wrightwood" },
  { key: "Yorba Linda", text: "Yorba Linda", value: "Yorba Linda" },
  { key: "Yosemite Lakes", text: "Yosemite Lakes", value: "Yosemite Lakes" },
  { key: "Yosemite Valley", text: "Yosemite Valley", value: "Yosemite Valley" },
  { key: "Yountville", text: "Yountville", value: "Yountville" },
  { key: "Yreka", text: "Yreka", value: "Yreka" },
  { key: "Yuba City", text: "Yuba City", value: "Yuba City" },
  { key: "Yucaipa", text: "Yucaipa", value: "Yucaipa" },
  { key: "Yucca Valley", text: "Yucca Valley", value: "Yucca Valley" }
];

export default CityList;
